### ISSUE TITLE
About Scheduled Jobs

### ISSUE THREAD

**Issue by qiaofeng1227** [espocrm/espocrm-docker#43]
【Add this line to the crontab file to run Espo Scheduled Jobs】：What does this note mean？

Is it for me to manually add [* * * * * cd /var/www/html; /usr/local/bin/php -f cron.php > /dev/null 2>&1] in the crontab of the operating system？

Or it has no other meaning, just an example。

**Comment by qiaofeng1227** [comment]
![image](https://github.com/espocrm/espocrm-docker/assets/43192516/8497af25-c0c9-4d30-8028-e7a9167881b7)

**Comment by lazespo** [comment]
This line indicates the location of the file responsible for the cron performance.

In general, there are two options for running a cron for EspoCRM in a Docker environment:

1. Using the `espocrm-daemon` container. The most convenient way to use it is in a *docker-compose.yml* file, which is presented [here](https://github.com/espocrm/espocrm-docker?tab=readme-ov-file#usage). Example:

```
 espocrm-daemon:
    image: espocrm/espocrm
    container_name: espocrm-daemon
    volumes:
      - espocrm:/var/www/html
    restart: always
    depends_on:
      - espocrm
    entrypoint: docker-daemon.sh
```   

2. Adding the following line to the crontab as a root user:

```
* * * * * /usr/bin/docker exec --user www-data -i espocrm /bin/bash -c "cd /var/www/html; /usr/local/bin/php -f cron.php" > /dev/null 2>&1
```
