### ISSUE TITLE
Option to specify Database port prevents use on most hosts

### ISSUE THREAD

**Issue by andrewvaughan** [espocrm/espocrm-docker#48]
Nearly all managed database providers use non-standard ports, but there is no `ESPOCRM_DATABASE_PORT` option. This prevents every hosting use-case except for self-hosted containers (which is a really, really bad idea in production).

I would personally treat this as urgent...

Closing https://github.com/espocrm/espocrm/issues/3074 as I believe this belongs here.

**Comment by andrewvaughan** [comment]
It's possible the intent is to have the port included in the `HOST` parameter, but this is counterintuitive (and against pretty much every other Docker configuration standard). It should be clearly documented, if this is the case.

**Comment by lazespo** [comment]
Hi @andrewvaughan,

When using EspoСRM in Docker or using a `docker-compose.yml` file, you usually do not need to set port for database. For example, we can use the following commands to deploy MySQL and EspoCRM in Docker and then link them to each other:

```
docker run --name mysql -e MYSQL_ROOT_PASSWORD=password -d mysql:8
docker run --name my-espocrm --link mysql:mysql -d espocrm/espocrm
```

In the same way, we can use the following containers in the `docker-compose.yml` file to use EspoCRM with MySQL:

```
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: espocrm
      MYSQL_USER: espocrm
      MYSQL_PASSWORD: database_password
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: mysql
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: database_password
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: password
      ESPOCRM_SITE_URL: "http://localhost:8080"
    volumes:
      - espocrm:/var/www/html
    restart: always
    ports:
      - 8080:80
```

If your container for MySQL is hosted on some third-party port (not 3306) or your database is hosted on some third-party server with a separate non-standard port, then you can set the following variable in the container for EspoCRM:

```
ESPOCRM_DATABASE_HOST: espocrm-mysql:3307
```

- `espocrm-mysql` — host
- `3307` — port 

```
ESPOCRM_DATABASE_HOST: 111.222.33.44:3307
```

- `111.222.33.44` — host
- `3307` — port
