### ISSUE TITLE
500 error with docker compose and existing mysql

### ISSUE THREAD

**Issue by 7aklhz** [espocrm/espocrm-docker#55]
Hi. 

I'm struggling to get espoCRM running with an existing mysql database and docker compose. This is what I have

```
services:
  espocrm:
    image: espocrm/espocrm
    container_name: espocrm
    environment:
      ESPOCRM_DATABASE_PLATFORM: Mysql
      ESPOCRM_DATABASE_HOST: 172.20.0.99 //Docker container IP
      ESPOCRM_DATABASE_PORT: 3306 // custom port
      ESPOCRM_DATABASE_NAME: espocrm_db
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: "abc"
      ESPOCRM_ADMIN_USERNAME: xyz
      ESPOCRM_ADMIN_PASSWORD: "123"
      ESPOCRM_SITE_URL: "http://10.242.1.11:3044"
    networks:
      - myNetwork
    volumes:
      - espocrm:/var/www/html
    restart: always
    ports:
      - 3044:80

  espocrm-daemon:
    image: espocrm/espocrm
    container_name: espocrm-daemon
    volumes:
      - espocrm:/var/www/html
    restart: always
    networks:
      - myNetwork
    depends_on:
      - espocrm
    entrypoint: docker-daemon.sh

  espocrm-websocket:
    image: espocrm/espocrm
    container_name: espocrm-websocket
    environment:
      ESPOCRM_CONFIG_USE_WEB_SOCKET: "true"
      ESPOCRM_CONFIG_WEB_SOCKET_URL: "ws://10.242.1.11:8081"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBSCRIBER_DSN: "tcp://*:7777"
      ESPOCRM_CONFIG_WEB_SOCKET_ZERO_M_Q_SUBMISSION_DSN: "tcp://espocrm-websocket:7777"
    volumes:
      - espocrm:/var/www/html
    restart: always
    networks:
      - myNetwork
    depends_on:
      - espocrm
    entrypoint: docker-websocket.sh
    ports:
      - 8081:8080

volumes:
  espocrm:

networks:
  myNetwork:
    external: true
```    
    
   
This gives ma blanck page with 500 error. Any ideas why ? My gut feeling is that it has something to do with the mysql database or its connection.
